version: '3'
services:
  selenium:
    container_name: selenium-chrome
    image: selenium/standalone-chrome-debug:3.141.59-20210929
    ports:
      - 4444:4444
      - 5900:5900
    shm_size: "2gb"
  test-app:
    container_name: main
    build: ./main
    volumes:
      - ./main:/opt/app
    ports:
      - 8000:80
    tty: true